// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eWAN.Core.Infrastructure.Database;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20200322122114_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("eWAN.Core.Domains.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("eWAN.Core.Domains.Entities.Identity.User", b =>
                {
                    b.OwnsOne("eWAN.Core.Domains.ValueObjects.Identity.UserContacts", "contacts", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("emailAddress")
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("eWAN.Core.Domains.ValueObjects.Address", "homeAddress", b2 =>
                                {
                                    b2.Property<Guid>("UserContactsUserId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("barangay")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("city")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("region")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("street")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("subdivision")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("zip")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserContactsUserId");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserContactsUserId");
                                });

                            b1.OwnsOne("eWAN.Core.Domains.ValueObjects.PhoneNumber", "mobileNumber", b2 =>
                                {
                                    b2.Property<Guid>("UserContactsUserId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("areaCode")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("countryCode")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("extension")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("UserContactsUserId");

                                    b2.ToTable("users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserContactsUserId");
                                });
                        });

                    b.OwnsOne("eWAN.Core.Domains.ValueObjects.Identity.UserDetails", "details", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("firstName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("lastName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("middleName")
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("eWAN.Core.Domains.ValueObjects.Identity.UserGuardian", "guardian", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("mobileNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("name")
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
